# vim: nospell
#
# Basic template to test with GHC=[7.8, 7.10, 8.0]. Caches the 'stack' build
# directory to speed subsequent compilations.
#
language: minimal
# dist: trusty

cache:
  timeout: 600
  directories:
    - $HOME/.stack/snapshots
    - $HOME/.local/bin
    - .stack-work/install

before_cache:
  # - rm -rf $(stack path --local-install-root)/bin
  - rm -rf $(stack path --local-install-root)/doc

addons:
  apt:
    sources: &apt_sources
      - hvr-ghc
    packages: &apt_packages
      - alex-3.1.7
      - happy-1.19.5
      - libgmp-dev

matrix:
  fast_finish: true
  include:
    - env: GHC=8.6.3
      compiler: "GHC 8.6"

    - env: GHC=8.4.2
      compiler: "GHC 8.4"

    - env: GHC=8.2.2
      compiler: "GHC 8.2"

    - env: GHC=8.0.2
      compiler: "GHC 8.0"

before_install:
  - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
  - source .travis/install-stack.sh

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version
  - stack build --no-terminal --dry-run
  - travis_retry travis_wait 60 stack build --fast --jobs=2 --test --only-dependencies --no-run-tests --no-terminal

script:
  - stack build --fast --jobs=2 --test --no-run-tests --no-terminal --haddock --no-haddock-deps
  - stack test

after_success:
  - source .travis/update-accelerate-buildbot.sh

