# vim: nospell
#
# Basic template to test with GHC=[7.8, 7.10, 8.0]. Caches the 'stack' build
# directory to speed subsequent compilations.
#
language: minimal
dist: trusty
sudo: required

cache:
  timeout: 600
  directories:
    - $HOME/.stack/snapshots
    - .stack-work/install

before_cache:
  # - rm -rf $(stack path --local-install-root)/bin
  - rm -rf $(stack path --local-install-root)/doc

matrix:
  include:

    - env: GHC=8.0.2 CABAL=1.24
      compiler: "GHC 8.0"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ libgmp-dev, cabal-install-1.24, happy-1.19.5, alex-3.1.7 ] }}

    - env: GHC=8.2.2 CABAL=2.0
      compiler: "GHC 8.2"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ libgmp-dev, cabal-install-2.0,  happy-1.19.5, alex-3.1.7 ] }}

    - env: GHC=8.4.2 CABAL=2.0
      compiler: "GHC 8.4"
      addons: { apt: { sources: [ hvr-ghc ], packages: [ libgmp-dev, cabal-install-2.0,  happy-1.19.5, alex-3.1.7 ] }}

    # - env: GHC=head CABAL=head
    #   compiler: "GHC HEAD"
    #   addons: { apt: { sources: [ hvr-ghc ], packages: [ ghc-head, cabal-install-head, happy-1.19.5, alex-3.1.7 ] }}

  # allow_failures:
  #   - env: GHC=head CABAL=head

  fast_finish: true

before_install:
  - export PATH=/opt/cabal/$CABAL/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$HOME/.cabal/bin:$PATH
  - source .travis/install-stack.sh

install:
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - cabal --version
  - stack --version
  - stack build --dry-run
  - stack build --no-terminal --dry-run
  - travis_retry travis_wait 60 stack build --fast --jobs=2 --test --only-dependencies --no-run-tests --no-terminal

script:
  - stack build --fast --jobs=2 --test --no-run-tests --no-terminal --haddock --no-haddock-deps
  - stack test

after_success:
  - source .travis/update-accelerate-buildbot.sh

