#!/bin/bash

# Get cabal to load up ghci for us. This will set the environment appropriately
# if we have a local sandbox installation.
#
GHC="cabal exec ghc --"

GHC_FLAGS="$GHC_FLAGS
    --interactive
    -DACCELERATE_BOUNDS_CHECKS
    -DACCELERATE_INTERNAL_CHECKS
    -DACCELERATE_DEBUG"

     # -optP-include -optPdist/build/autogen/cabal_macros.h \

$GHC $GHC_FLAGS $@

