#!/bin/bash

# Adjust to the installed location of ghci, if this script can not find it.
#
GHC=`which -a ghc`
VER=`$GHC --numeric-version`
GHC_FLAGS="--interactive"


# We assume that the dependent packages are install with 'cabal'. If you have
# installed them with another tool such as 'cabal-dev', add the following to the
# command.
#
#    -package-conf cabal-dev/packages-$VER.conf

# And go...
#
$GHC $GHC_FLAGS \
     -DACCELERATE_BOUNDS_CHECKS \
     -DACCELERATE_INTERNAL_CHECKS \
     -DACCELERATE_DEBUG \
     $@

     # -optP-include -optPdist/build/autogen/cabal_macros.h \
